table:
  name: patient
  schema: public
object_relationships:
  - name: organization
    using:
      foreign_key_constraint_on: organizationId
  - name: primaryTherapistUser
    using:
      foreign_key_constraint_on: primaryTherapist
  - name: user
    using:
      foreign_key_constraint_on: onboardedBy
array_relationships:
  - name: games
    using:
      foreign_key_constraint_on:
        column: patient
        table:
          name: game
          schema: public
  - name: patient_notes
    using:
      foreign_key_constraint_on:
        column: patient
        table:
          name: patient_notes
          schema: public
  - name: sessions
    using:
      foreign_key_constraint_on:
        column: patient
        table:
          name: session
          schema: public
insert_permissions:
  - role: org_admin
    permission:
      check: {}
      set:
        organizationId: x-hasura-organization-id
      columns:
        - email
        - firstName
        - lastName
        - namePrefix
        - phoneCountryCode
        - phoneNumber
  - role: therapist
    permission:
      check: {}
      set:
        onboardedBy: x-hasura-user-id
        primaryTherapist: x-hasura-user-id
      columns:
        - careGiverEmail
        - careGiverPhoneCountryCode
        - careGiverPhoneNumber
        - careplan
        - email
        - identifier
        - medicalConditions
        - phoneCountryCode
        - phoneNumber
        - preferredGenres
select_permissions:
  - role: benchmark
    permission:
      columns:
        - canBenchmark
        - createdAt
        - id
        - identifier
        - nickname
        - preferredGenres
        - updatedAt
      filter: {}
  - role: org_admin
    permission:
      columns:
        - id
      filter:
        organizationId:
          _eq: x-hasura-organization-id
      allow_aggregations: true
  - role: patient
    permission:
      columns:
        - careGiverEmail
        - careGiverPhoneCountryCode
        - careGiverPhoneNumber
        - createdAt
        - email
        - firstName
        - id
        - identifier
        - lastName
        - medicalConditions
        - nickname
        - onboardedBy
        - onboardingStatus
        - phoneCountryCode
        - phoneNumber
        - preferredActivities
        - preferredGenres
        - primaryTherapist
        - rewards
        - timezone
        - updatedAt
      filter:
        id:
          _eq: X-Hasura-User-Id
  - role: sh_admin
    permission:
      columns:
        - id
      filter: {}
      allow_aggregations: true
  - role: therapist
    permission:
      columns:
        - careGiverEmail
        - careGiverPhoneCountryCode
        - careGiverPhoneNumber
        - careplan
        - createdAt
        - email
        - firstName
        - id
        - identifier
        - lastName
        - medicalConditions
        - namePrefix
        - nickname
        - onboardedBy
        - onboardingStatus
        - organizationId
        - phoneCountryCode
        - phoneNumber
        - preferredActivities
        - preferredGenres
        - primaryTherapist
        - rewards
        - status
        - timezone
        - type
        - updatedAt
      filter:
        organizationId:
          _eq: x-hasura-organization-id
      allow_aggregations: true
update_permissions:
  - role: benchmark
    permission:
      columns:
        - careGiverEmail
        - careGiverPhoneCountryCode
        - careGiverPhoneNumber
        - email
        - medicalConditions
        - nickname
        - onboardingStatus
        - password
        - phoneCountryCode
        - phoneNumber
        - preferredActivities
        - preferredGenres
        - timezone
      filter:
        id:
          _eq: X-Hasura-User-Id
      check: null
  - role: patient
    permission:
      columns:
        - careGiverEmail
        - careGiverPhoneCountryCode
        - careGiverPhoneNumber
        - email
        - medicalConditions
        - nickname
        - onboardingStatus
        - password
        - phoneCountryCode
        - phoneNumber
        - preferredActivities
        - preferredGenres
        - timezone
      filter:
        id:
          _eq: X-Hasura-User-Id
      check: null
  - role: therapist
    permission:
      columns:
        - email
        - firstName
        - lastName
        - namePrefix
        - phoneCountryCode
        - phoneNumber
        - status
      filter:
        organizationId:
          _eq: x-hasura-organization-id
      check: null
event_triggers:
  - name: event_added_first_patient
    definition:
      enable_manual: true
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{ACTION_BASE_URL}}/events/therapist/added-first-patient'
    headers:
      - name: x-hasura-admin-secret
        value_from_env: EVENTS_SECRET
    request_transform:
      body:
        action: transform
        template: |-
          {
            "id": {{$body.event.data.new.id}},
            "identifier": {{$body.event.data.new.identifier}},
            "primaryTherapist": {{$body.event.data.new.primaryTherapist}}
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: event_new_patient
    definition:
      enable_manual: true
      insert:
        columns: '*'
      update:
        columns:
          - id
          - email
          - nickname
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{ACTION_BASE_URL}}/events/patient/new'
    headers:
      - name: x-hasura-admin-secret
        value_from_env: EVENTS_SECRET
    request_transform:
      body:
        action: transform
        template: |-
          {
            "id": {{$body.event.data.new.id}},
            "email": {{$body.event.data.new.email}},
            "nickname": {{$body.event.data.new.nickname}}
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
