table:
  name: game_benchmark_config
  schema: public
object_relationships:
  - name: game
    using:
      foreign_key_constraint_on: originalGameId
insert_permissions:
  - role: benchmark
    permission:
      check: {}
      columns:
        - manualCalculations
        - originalGameId
select_permissions:
  - role: benchmark
    permission:
      columns:
        - manualCalculations
        - rawVideoUrl
        - screenRecordingUrl
        - createdAt
        - updatedAt
        - id
        - originalGameId
      filter: {}
update_permissions:
  - role: benchmark
    permission:
      columns:
        - manualCalculations
      filter: {}
      check: null
